#!/usr/bin/env bash
# qa.sh — automated quality gate for the build (stage 05).
#
# Runs the mechanical checks (lint, typecheck, build) and collates a report the
# review stage reads. Non-fatal by design: it records every result so the agent
# can triage, rather than stopping at the first failure. Judgement checks
# (accessibility, brand/spec fidelity) are done by the agent against the checklist
# in stages/05_review/references/qa-checklist.md.

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

REPORT="pipeline/stages/05_review/output/qa-results.md"
mkdir -p "$(dirname "$REPORT")"

if [ ! -f "package.json" ]; then
  echo "qa: no package.json at repo root — build the app (stage 04) first." >&2
  exit 1
fi

# Pick the package manager actually used.
if [ -f "pnpm-lock.yaml" ] && command -v pnpm >/dev/null 2>&1; then
  PM="pnpm"
elif command -v npm >/dev/null 2>&1; then
  PM="npm run"
else
  echo "qa: no pnpm/npm found on PATH." >&2
  exit 1
fi

run_step() {
  local name="$1"; shift
  echo "" | tee -a "$REPORT"
  echo "## $name" | tee -a "$REPORT"
  echo '```' >> "$REPORT"
  if "$@" >>"$REPORT" 2>&1; then
    echo '```' >> "$REPORT"
    echo "**$name: PASS**" | tee -a "$REPORT"
    return 0
  else
    echo '```' >> "$REPORT"
    echo "**$name: FAIL** — see output above." | tee -a "$REPORT"
    return 1
  fi
}

# Fresh report header.
{
  echo "# QA results"
  echo ""
  echo "Generated by qa.sh. Manual checks (a11y, brand, spec, security) are in"
  echo "review-report.md per qa-checklist.md."
} > "$REPORT"

STATUS=0

# Lint (script may be named "lint").
if grep -q '"lint"' package.json; then
  run_step "Lint" $PM lint || STATUS=1
else
  echo "" >> "$REPORT"; echo "## Lint" >> "$REPORT"; echo "_no lint script_" >> "$REPORT"
fi

# Type check (prefer tsc --noEmit; fall back to a typecheck script).
if command -v npx >/dev/null 2>&1 && [ -f "tsconfig.json" ]; then
  run_step "Type check" npx --yes tsc --noEmit || STATUS=1
elif grep -q '"typecheck"' package.json; then
  run_step "Type check" $PM typecheck || STATUS=1
else
  echo "" >> "$REPORT"; echo "## Type check" >> "$REPORT"; echo "_no typescript config_" >> "$REPORT"
fi

# Production build.
if grep -q '"build"' package.json; then
  run_step "Build" $PM build || STATUS=1
else
  echo "" >> "$REPORT"; echo "## Build" >> "$REPORT"; echo "_no build script_" >> "$REPORT"
fi

echo "" | tee -a "$REPORT"
if [ "$STATUS" -eq 0 ]; then
  echo "qa: all automated checks passed. Report: $REPORT"
else
  echo "qa: some checks failed — triage and fix, then re-run. Report: $REPORT"
fi

# Reminder for the agent's manual passes.
cat <<'EOF'

qa: next, run the manual passes from stages/05_review/references/qa-checklist.md:
    - accessibility (apply the `accessibility` skill)
    - brand fidelity (vs 01_brand/output)
    - spec fidelity (vs 02_spec/output/spec.md)
    - performance notes (Lighthouse / next build output)
EOF

exit "$STATUS"
